name: Deploy
on:
  push:
    branches:
      - main
jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: 'Block Concurrent Executions'
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/knowit.b24online.com && . deploy.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
